/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    tenants: Tenant;
    pages: Page;
  };
  globals: {};
}
export interface User {
  id: string;
  firstName?: string;
  lastName?: string;
  roles: ('super-admin' | 'user')[];
  tenants?: {
    tenant: string | Tenant;
    roles: ('admin' | 'user')[];
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Tenant {
  id: string;
  name: string;
  slug?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Page {
  id: string;
  title: string;
  slug?: string;
  tenant: string | Tenant;
  richText: {
    [k: string]: unknown;
  }[];
  updatedAt: string;
  createdAt: string;
}
